### ISSUE TITLE
Thanks for putting this together

### ISSUE THREAD

**Issue by austinrivas** [vmunier/play-with-scalajs-example#28]
It has really helped my get a handle on all the play / scalajs build process.

Right now this package seems like the best practice for integrating scalajs / play, and I plan on using it as the foundation for a project.

Do you know of any potential gotchas that I may encounter while dev'ing with this project setup?

A few small things I noticed while setting up the project in IntelliJ : 

* open the project directly results in intellij converting it from an sbt to a gen-idea project
* importing project as an sbt project works fine
* importing */project/project as an sbt task works fine
* source maps work like a charm!

**Comment by vmunier** [comment]
Hi @austinrivas 
The only issue I can think of is the IntelliJ integration. It does not work well with cross projects for now but the IDEA team is working on a fix. 
For your information, there is a pending PR which will change the structure of the Build so you might want to look at the [sbt-play-scalajs-v0.2.x branch](https://github.com/vmunier/play-with-scalajs-example/tree/sbt-play-scalajs-v0.2.x) instead of master.

P.S.: For next time I recommend posting your question on the chat https://gitter.im/vmunier/play-with-scalajs-example or on the Scala.js mailing list. Opening an issue is more for a bug found or a missing feature ;)

**Comment by austinrivas** [comment]
Will do, thanks for the quick response!

How long do you think it will be until the pr is merged?

**Comment by vmunier** [comment]
Less than 2 days I guess, but you don't have to wait, just use the branch as a base...

**Comment by austinrivas** [comment]
Going to do that now, feel free to delete this issue btw. Hanging gh issues drive me crazy too.
