### ISSUE TITLE
Example fails to run due to type error

### ISSUE THREAD

**Issue by outkaj** [vmunier/play-with-scalajs-example#49]
After downloading the application and following instructions in the README, I receive the following error: 

`../play-with-scalajs-example-master/build.sbt:24: error: type mismatch;
 found   : String("org.scala-js")
 required: ?{def %%%(x$1: ? >: String("scalajs-dom")): ?}
Note that implicit conversions are not applicable because they are ambiguous:
 both method toCrossGroupID in object AutoImport of type (groupID: String)sbtcrossproject.CrossGroupID
 and method toScalaJSGroupID in trait DependencyBuilders of type (groupID: String)org.scalajs.sbtplugin.impl.ScalaJSGroupID
 are possible conversion functions from String("org.scala-js") to ?{def %%%(x$1: ? >: String("scalajs-dom")): ?}
    "org.scala-js" %%% "scalajs-dom" % "0.9.1"
    ^
../play-with-scalajs-example-master/build.sbt:24: error: value %%% is not a member of String
    "org.scala-js" %%% "scalajs-dom" % "0.9.1"
                   ^
../play-with-scalajs-example-master/build.sbt:29: error: reference to crossProject is ambiguous;
it is imported twice in the same scope by
import _root_.org.scalajs.sbtplugin.ScalaJSPlugin.autoImport._
and import _root_.sbtcrossproject.CrossPlugin.autoImport._
lazy val shared = (crossProject.crossType(CrossType.Pure) in file("shared")).
                   ^
sbt.compiler.EvalException: Type error in expression
[error] sbt.compiler.EvalException: Type error in expression
`

Any ideas as to the best way to resolve this? 

I'm running Java 1.8 and Scala 2.12.1. Let me know if there is other information I can provide which may be helpful.

**Comment by vmunier** [comment]
Hi,
Do you have global sbt plugins, in `~/.sbt/.../plugins/`, which could create conflicts?

**Comment by outkaj** [comment]
Here is the content of the (global) plugins.sbt:

`addSbtPlugin("org.ensime" % "sbt-ensime" % "1.12.7")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.8.2")`

Thank you for your help.

**Comment by vmunier** [comment]
I cannot reproduce your error, but looking at the error you pasted, sbt is confused because there are two crossProjects being imported, one from Scala.js (`import _root_.org.scalajs.sbtplugin.ScalaJSPlugin.autoImport._ `) and one from sbt itself (`import _root_.sbtcrossproject.CrossPlugin.autoImport._`).

Could you try to move temporarily your `~/.sbt` folder (`mv ~/.sbt ~/.sbt-save`) just to see wether the problem comes from some definitions in this folder or not?

Even though not related to the error you see, please note that you'll not be able to use Scala 2.12.1 because the Play framework has not yet been released for Scala 2.12. Play framework 2.6.x will support Scala 2.12 but is still in development.

**Comment by outkaj** [comment]
The problem did in fact come from definitions in the `~/.sbt` folder, as you suspected. Once I removed `addSbtPlugin("org.scala-native" % "sbt-scala-native"  % "0.1.0")` from the global build.sbt, the example ran as expected in the browser and the issue is now resolved. 

Thanks for your prompt help and also for the heads-up re: needing to wait for Play 2.6 for Scala 2.12 support.

**Comment by vmunier** [comment]
Glad I could help!
